# Generated by Django 3.0.3 on 2021-05-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='username',
        ),
    ]
