# Generated by Django 3.0.3 on 2021-05-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210513_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
